server:
  port: 8082

spring:
  application:
    name: AIGOU-ZUUL



#路由配置
zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  prefix: /services
  routes:
    plat:
      serviceId: AIGOU-PLAT
      path: /plat/**
    product:
      serviceId: AIGOU-PRODUCT
      path: /product/**
    common:
      serviceId: AIGOU-COMMON
      path: /common/**
  